import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "@/app/providers";
import Header from '@/Components/homeComponents/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"bg-[#180828]"}>
      <body className={inter.className}>
      <Providers>
          <main className={"dark text-foreground bg-background"}>
            <Header/>
              {children}
          </main>
      </Providers>
      </body>
    </html>
  )
}
